module.exports = {
  apps: [
    {
      name: "ekosistem-sosyal-backend",
      cwd: "/var/www/ekosistem-sosyal-medya/backend",
      interpreter: "none",
      script: "/home/orhan/.bun/bin/bun",
      args: "dist/index.js",
      exec_mode: "fork",
      instances: 1,
      watch: false,
      autorestart: true,
      max_memory_restart: "650M",
      min_uptime: "30s",
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 8000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",
        PORT: "8089",
      },
      out_file: "/home/orhan/.pm2/logs/ekosistem-sosyal-backend.out.log",
      error_file: "/home/orhan/.pm2/logs/ekosistem-sosyal-backend.err.log",
      combine_logs: true,
      time: true,
    },
    {
      name: "ekosistem-sosyal-dashboard",
      cwd: "/var/www/ekosistem-sosyal-medya/dashboard",
      interpreter: "none",
      script: "/home/orhan/.bun/bin/bun",
      args: "run start -- -p 3035 -H 127.0.0.1",
      exec_mode: "fork",
      instances: 1,
      watch: false,
      autorestart: true,
      max_memory_restart: "450M",
      min_uptime: "30s",
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 8000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: "production",
        PORT: "3035",
        HOSTNAME: "127.0.0.1",
        NEXT_TELEMETRY_DISABLED: "1",
      },
      out_file: "/home/orhan/.pm2/logs/ekosistem-sosyal-dashboard.out.log",
      error_file: "/home/orhan/.pm2/logs/ekosistem-sosyal-dashboard.err.log",
      combine_logs: true,
      time: true,
    },
  ],
};
